version: '2'
services:
  # The Application
  php:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
        - .:/var/www

  # The Web Server
  nginx:
    working_dir: /var/www
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - 8765:80

